# Console pipeline sh / api.sh

pipelines:
  branches:
    staging: 
      - step:
          name: Deploy API to staging
          deployment: staging
          script:
            - echo "Deploying to staging environment"
            - pipe: atlassian/ssh-run:0.2.2
              variables:
                SSH_USER: $SSH_USER
                SERVER: $SERVER
                PORT: $PORT
                COMMAND: "bash ~/runners/api.sh" 
            - echo "Done" 