module.exports = {
	login_error: 'error_message_invalid_phone_number_or_password',
	login_check_error: 'error_message_invalid_number_or_code',
	digit_code_check: 'ok',
	digit_code_send_err: 'error_message_cant_send_code',
	verified_error: 'error_message_already_signin',
	digit_code_error: 'error_message_invalid_code',
	login: 'ok',
	not_authenticate: 'User not authenticated',
	not_found: 'Not found',
	nothing_updated: 'nothing_updated',
	nothing_deleted: 'nothing_deleted',
	phone_err: {phoneNumber: "error_message_phone_number_already_busy"},
	username_err: {username: "Username_already_busy"},
	user_create: "user_created",
	driver_create: "driver_created",
	driver_exist: "error_message_driver_already_busy",
	email_err: "error_message_email_already_busy",
	number_exist: "error_message_number_already_busy",
	perm_err: 'Permission denied',
	user_update: 'user_updated',
	driver_update: 'driver_updated',
	user_delete: 'user_deleted',
	deleted_user: 'cant_change_deleted_user',
	driver_delete: 'driver_deleted',
	not_auth: 'error_message_not_authorized',
	forbidden: 'error_message_not_permission',
	location_create: 'country_created',
	country_exist: 'error_message_country_already_exist',
	city_exist: 'error_message_city_already_exist',
	location_update: 'country_updated',
	location_delete: 'country_deleted',
	country_del_err: 'This country has cities',
	city_create: 'city_created',
	city_update: 'city_updated',
	city_delete: 'city_deleted',
	city_has_route: 'This city has route',
	route_create: 'route_created',
	route_delete: 'route_deleted',
	route_has_service: 'This route has service',
	partner_create: 'partner_created',
	partner_delete: 'partner_deleted',
	partner_update: 'partner_updated',
	service_create: 'service_created',
	service_update: 'service_updated',
	service_delete: 'service_deleted',
	service_has_ticket: 'This service has ticket',
	ticket_create: 'ticket_created',
	ticket_update: 'ticket_updated',
	ticket_delete: 'ticket_deleted',
	passenger_delete: 'passenger_deleted',
	ticketDetail_delete: 'ticket_detail_deleted',
	available_count_error: 'error_message_available_count_error',
	ref_error: 'This referral already exist',
	user_exist_err: 'No such user',
	user_not_found: 'user_not_found',
	city_exist_err: 'No such city',
	country_exist_err: 'No such country',
	route_exist_err: 'No such route',
	driver_exist_err: 'No such driver',
	service_exist_err: 'No such service',
	partner_exist_err: 'No such partner',
	pBranch_exist_err: 'No such partner branch',
	invitor_exist_err: {invitor: 'No such user'},
	timeout_exp: 'Wait timeout expired',
	not_full_verified: 'User not full verified',
	partner_branch_delete: 'Partner branch deleted',
	choose_password: 'error_message_dont_have_password',
	check_registration: 'check_registration',
	registration_checked: 'signup_checked_set_password',
	user_not_verified: 'error_message_user_not_verified',
	check_forgot: 'check_forgot_code',
	forgot_checked: 'forgot_checked_set_password',
	password_changed: 'password_changed',
	create_delivery_service: 'delivery_service_created',
	update_delivery_service: 'delivery_service_updated',
	delivery_service_up_status_err: 'error_message_delivery_service_update_status_error',
	delivery_service_status: 'delivery_service_status_changed',
	delivery_service_not_found: 'error_message_no_such_delivery_service',
	error_message_phoneNumber: 'error_message_invalid_phoneNumber',
	error_message_password: 'error_message_invalid_password',
	error_message_code: 'error_message_invalid_code',
	error_message_refreshToken: 'error_message_invalid_refreshToken',
	error_message_page: 'error_message_invalid_page',
	error_message_startDate: 'error_message_invalid_startDate',
	error_message_endDate: 'error_message_invalid_endDate',
	error_message_id: 'error_message_invalid_id',
	error_message_partner: 'error_message_invalid_partner',
	error_message_partnerBranchId: 'error_message_invalid_partnerBranchId',
	error_message_driver: 'error_message_invalid_driver',
	error_message_paymentMethod: 'error_message_invalid_paymentMethod',
	error_message_isOrderForAnother: 'error_message_invalid_isOrderForAnother',
	error_message_senderName: 'error_message_invalid_senderName',
	error_message_senderPhoneNumber: 'error_message_invalid_senderPhoneNumber',
	error_message_senderAddress: 'error_message_invalid_senderAddress',
	error_message_senderCoordinates: 'error_message_invalid_senderCoordinates',
	error_message_deliveryAddress: 'error_message_invalid_deliveryAddress',
	error_message_deliveryCoordinates: 'error_message_invalid_deliveryCoordinates',
	error_message_customerName: 'error_message_invalid_customerName',
	error_message_customerPhoneNumber: 'error_message_invalid_customerPhoneNumber',
	error_message_orderPrice: 'error_message_invalid_orderPrice',
	error_message_status: 'error_message_invalid_status',
	error_message_coords: 'error_message_invalid_coords',
	authenticate_err: 'error_message_not_authenticated',
	user_exist_error: 'error_message_no_such_user',
	phone_exist_error: 'error_message_phone_number_already_busy',
	partner_exist_error: 'error_message_no_such_partner',
	partner_already_exist: 'partner_already_exist',
	pBranch_exist_error: 'error_message_no_such_partner_branch',
	driver_exist_error: 'error_message_no_such_driver',
	error_message_fromCity: 'error_message_invalid_fromCity',
	error_message_toCity: 'error_message_invalid_toCity',
	error_message_city: 'error_message_invalid_city',
	error_message_country: 'error_message_invalid_country',
	country_exist_error: 'error_message_no_such_country',
	city_exist_error: 'error_message_no_such_city',
	service_exist_error: 'error_message_no_such_service',
	error_message_osType: 'error_message_invalid_osType',
	error_message_deviceToken: 'error_message_invalid_deviceToken',
	error_message_deviceId: 'error_message_invalid_deviceId',
	device_exist_error: 'error_message_device_already_exist',
	payment_success: 'payment_succeeded',
	payment_fail: 'payment_failed',
	deleted_change: 'deleted_changed',
	transport_create: 'transport_created',
	transport_update: 'transport_updated',
	transport_delete: 'transport_deleted',
	deliveryService_delete: 'deliveryService_deleted',
	push_notification_fail: 'push_notification_fail',
	order_fail: 'order_failed',
	device_create: 'device_created',
	service_error: 'error_message_invalid_service',
	serviceType_error: 'error_message_invalid_serviceType',
	details_error: 'error_message_invalid_details',
	isChildPassenger_error: 'error_message_invalid_isChildPassenger',
	state_error: 'error_message_invalid_state',
	fromCity_error: 'error_message_invalid_fromCity',
	toCity_error: 'error_message_invalid_toCity',
	fromAddress_error: 'error_message_invalid_fromAddress',
	toAddress_error: 'error_message_invalid_toAddress',
	passengerPhoneNumber_error: 'error_message_invalid_passengerPhoneNumber',
	passengerSeat_error: 'error_message_invalid_passengerSeat',
	kg_error: 'error_message_invalid_kg',
	description_error: 'error_message_invalid_description',
	senderPhoneNumber_error: 'error_message_invalid_senderPhoneNumber',
	receiverPhoneNumber_error: 'error_message_invalid_receiverPhoneNumber',
	promoCode_error: 'error_message_invalid_promoCode',
	method_error: 'error_message_invalid_method',
	price_error: 'error_message_invalid_price',
	status_error: 'error_message_invalid_status',
	orderId_error: 'error_message_invalid_orderId',
	device_delete: 'device_deleted',
	client_already_exist: 'client_already_exist',
	client_create: 'client_created',
	client_update: 'client_updated',
	client_delete: 'client_deleted',
	partner_subscribe_err: 'partner_subscribe_err',
};
